"""create analyses table

Revision ID: 2e3b7f05fccf
Revises: e18cc744ca70
Create Date: 2026-02-20 14:14:36.981758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3b7f05fccf'
down_revision: Union[str, Sequence[str], None] = 'e18cc744ca70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('hire_recommendation', sa.Boolean(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('total_experience_years', sa.Float(), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_candidate_name'), 'analyses', ['candidate_name'], unique=False)
    op.create_index(op.f('ix_analyses_hire_recommendation'), 'analyses', ['hire_recommendation'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_job_id'), 'analyses', ['job_id'], unique=False)
    op.create_index(op.f('ix_analyses_overall_score'), 'analyses', ['overall_score'], unique=False)
    op.create_index(op.f('ix_analyses_recommendation'), 'analyses', ['recommendation'], unique=False)
    op.create_index(op.f('ix_analyses_resume_id'), 'analyses', ['resume_id'], unique=False)
    op.create_index(op.f('ix_analyses_total_experience_years'), 'analyses', ['total_experience_years'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_total_experience_years'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_resume_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_recommendation'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_overall_score'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_job_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_hire_recommendation'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_candidate_name'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
