"""remove hire_recommendation column

Revision ID: a4a5ff9e72aa
Revises: 2e3b7f05fccf
Create Date: 2026-02-20 15:03:44.087513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a5ff9e72aa'
down_revision: Union[str, Sequence[str], None] = '2e3b7f05fccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_hire_recommendation'), table_name='analyses')
    op.drop_column('analyses', 'hire_recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('hire_recommendation', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_analyses_hire_recommendation'), 'analyses', ['hire_recommendation'], unique=False)
    # ### end Alembic commands ###
